### ISSUE TITLE
Crear componente para Carrousel

### ISSUE THREAD

**Issue by facundolaso** [facundolaso/mytinerary-404error#10]
Debe tener un título "Popular MYtineraries"
Debe contener 3 slides de 4 fotos cada una / Son 12 ciudades repartidas en 3 slides de 4 c/u.
Cada foto debe corresponder a una ciudad del mundo y debe estar su nombre en inglés.
Como no disponemos de base de datos: las fotos/nombres van a estar hardcodeados en el componente.
El renderizado debe ser DINÁMICO. No debe estar hardcodeado el código que muestra las slides con sus fotos.

**Comment by engelberthRetamal** [comment]
Como usuario 
Quiero poder ver un carrusel
Para dar un vistazo a las fotos y nombres de las ciudades
