### ISSUE TITLE
Modificar Footer

### ISSUE THREAD

**Issue by facundolaso** [facundolaso/mytinerary-404error#29]
Para incluir un botón que suba al inicio de la página
Debería contener otro menú de navegación para facilitarle la navegacion al usuario
Opcional: Mostrar el año con el objeto Date
Opcional: Agregar un boton de scroll to top

**Comment by engelberthRetamal** [comment]
Como usuario
Quiero tener un botón 
Para subir al principio de la página en la que estoy
